"""Regenerate the HTML named character reference table.

The spec's list is fixed and published as a machine-readable file, so the table
is generated from it rather than typed. Run this when the spec updates:

    python tools/gen_entities.py

It writes crates/zero-engine/src/entities.rs, which is committed — the build
does not reach the network.
"""

import json
import pathlib
import urllib.request

SOURCE = "https://html.spec.whatwg.org/entities.json"
OUT = pathlib.Path(__file__).resolve().parent.parent / "crates/zero-engine/src/entities.rs"


def rust_str(text):
    out = ['"']
    for ch in text:
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ord(ch) < 0x20 or ord(ch) > 0x7E:
            out.append("\\u{%x}" % ord(ch))
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def main():
    with urllib.request.urlopen(SOURCE) as response:
        entities = json.load(response)

    # Keys arrive as "&name;" / "&name"; the table stores the bare name so the
    # lookup can match with or without the semicolon in one pass.
    rows = sorted((name.lstrip("&"), "".join(chr(c) for c in body["codepoints"]))
                  for name, body in entities.items())
    longest = max(len(name) for name, _ in rows)

    lines = [
        "// @generated by tools/gen_entities.py from %s — do not edit by hand." % SOURCE,
        "//",
        "// The HTML named character references, all %d of them. The name is stored" % len(rows),
        "// with its trailing semicolon where the spec gives it one, because about a",
        "// hundred of them are also valid without: `&amp` and `&copy` are references,",
        "// and only the table says which. A handful expand to two code points, so the",
        "// value is a string rather than a char.",
        "",
        "/// Every named reference, sorted by name for binary search.",
        "pub(crate) const NAMED: &[(&str, &str)] = &[",
    ]
    for name, value in rows:
        lines.append("    (%s, %s)," % (rust_str(name), rust_str(value)))
    lines.append("];")
    lines.append("")
    lines.append("/// The longest name in the table, which bounds the longest-match scan.")
    lines.append("pub(crate) const LONGEST: usize = %d;" % longest)
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print("wrote %s (%d entries, longest %d)" % (OUT, len(rows), longest))


if __name__ == "__main__":
    main()
